default: &default
  adapter: sqlite3
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  host: 127.0.0.1

development:
  <<: *default
  database: cvecara.sqlite

test:
  <<: *default
  database: cvecara_test.sqlite

# problem with mac
# default: &default
#   adapter: mysql2
#   encoding: utf8mb4
#   username: root
#   password: # null
#   database: cveacara_rails
#   host: localhost
#   socket: /tmp/mysql.sock                                  # mysql socket path gotten with 'mysql_config --socket'
#   pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>