default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  # baza i myappuser su na 3307 portu
  username: myappuser
  password: myapppassword
  host: 127.0.0.1
  port: 3307

development:
  <<: *default
  database: cvecara_rails
  # database: ../db/cvecara.sqlite - before mysql

test:
  <<: *default
  database: cvecara_rails_test